# Generated by Django 4.0.6 on 2022-08-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thirdparty',
            old_name='account',
            new_name='account_a',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='destination_account',
            new_name='destinationaccount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='origin_account',
            new_name='originaccount',
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='status',
            field=models.CharField(choices=[('r', 'read'), ('u', 'unread')], max_length=7, null=True),
        ),
    ]
