# Generated by Django 4.0.6 on 2022-08-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_rename_account_thirdparty_account_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='notifcation',
            old_name='Message',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='card',
            name='card_security_code',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='card',
            name='issuer',
            field=models.CharField(max_length=33),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='status',
            field=models.CharField(choices=[('r', 'active'), ('u', 'passive')], max_length=7, null=True),
        ),
    ]
