# Generated by Django 4.0.6 on 2022-08-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_rename_amount_loan_loan_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='destinationaccount',
            new_name='destination_account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='originaccount',
            new_name='origin_account',
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.BigIntegerField(),
        ),
    ]
