# Generated by Django 4.0.6 on 2022-07-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField()),
                ('card_holder_name', models.CharField(max_length=23)),
                ('expiry_date', models.DateTimeField()),
                ('card', models.CharField(choices=[('D', 'debit'), ('C', 'credit')], max_length=6, null=True)),
                ('card_security_code', models.CharField(max_length=5)),
                ('issuer', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('loan_type', models.CharField(choices=[('Faulu', 'Mshwari'), ('Tala', 'fuliza')], max_length=10, null='True')),
                ('interest_rate', models.SmallIntegerField()),
                ('Date', models.DateTimeField()),
                ('loan_Id', models.CharField(max_length=30)),
                ('loan_term', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Notifcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=10000)),
                ('title', models.CharField(max_length=900)),
                ('date', models.DateTimeField()),
                ('notifiaction_type', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('r', 'read'), ('u', 'unread')], max_length=7, null='True')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateTimeField()),
                ('receipt_number', models.CharField(max_length=6)),
                ('total_amount', models.IntegerField()),
                ('receipt_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_code', models.CharField(max_length=14)),
                ('transaction_charge', models.IntegerField()),
                ('transaction_amount', models.IntegerField()),
                ('transaction_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Walletb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_supported', models.CharField(max_length=27)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.PositiveIntegerField(),
        ),
    ]
