# Generated by Django 4.0.6 on 2022-09-02 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_rename_destinationaccount_transaction_destination_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Address',
            new_name='address',
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
    ]
