# Generated by Django 4.0.6 on 2022-10-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_rename_address_customer_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card',
            field=models.CharField(choices=[('Debit', 'debit'), ('credit', 'credit')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='notifcation',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('passive', 'passive')], max_length=7, null=True),
        ),
    ]
